# PostgreSQL. Versions 12.0 and up are supported.
#   gem install pg
#
#   Ensure the PostgreSQL gem is defined in your Gemfile
#   gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: volunteer_board_development

test:
  <<: *default
  database: volunteer_board_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
