test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

r2:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:s3, Rails.env.to_sym, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:s3, Rails.env.to_sym, :secret_access_key) %>
  region: auto
  bucket: <%= Rails.application.credentials.dig(:s3, Rails.env.to_sym, :bucket) %>
  endpoint: <%= Rails.application.credentials.dig(:s3, Rails.env.to_sym, :endpoint_url) %>
  request_checksum_calculation: "when_required"
  response_checksum_validation: "when_required"
